version: "3.8"

services:
  mail:
    image: mailhog/mailhog
    ports:
      - "8025:8025"
      - "1025:1025"
    environment:
      - MH_UI_WEB_PATH=mail

  redis:
    image: redis:alpine
    restart: always
    ports:
      - "6379:6379"
