name: tests
on: push

jobs:
  tests:
    runs-on: ubuntu-latest

    services:

      redis:
        image: redis:latest
        ports:
          - 6379:6379
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 2s
          --health-timeout 1s
          --health-retries 5
          --name redis

      mail:
        image: mailhog/mailhog
        ports:
          - 8025:8025
          - 1025:1025
        env:
          MH_UI_WEB_PATH: mail

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-go@v1
        with:
          go-version: '1.15'

      - name: Tests
        run: go test ./...